Traceback (most recent call last):
  File "/Users/haoluncheng/Desktop/FkCareerPUA/Project/backend/server.py", line 743, in <module>
    run()
  File "/Users/haoluncheng/Desktop/FkCareerPUA/Project/backend/server.py", line 738, in run
    httpd = server_class(server_address, handler_class)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/socketserver.py", line 473, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 48] Address already in use
